# Generated by Django 4.1.5 on 2023-01-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abrigo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('fotos', models.ImageField(upload_to='static')),
                ('endereco', models.CharField(max_length=100)),
                ('redes_sociais', models.CharField(max_length=100)),
            ],
        ),
    ]
