# Generated by Django 4.1.5 on 2023-01-10 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LarParaSempre', '0005_alter_abrigo_fotos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('fotos', models.ImageField(upload_to='Pet')),
                ('idade', models.IntegerField()),
                ('especie', models.CharField(max_length=20)),
                ('raca', models.CharField(max_length=20)),
                ('sexo', models.CharField(max_length=1)),
                ('abrigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LarParaSempre.abrigo')),
            ],
        ),
    ]
