# Generated by Django 4.1.5 on 2023-01-12 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LarParaSempre', '0006_pet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abrigo',
            options={'verbose_name': 'Abrigo'},
        ),
    ]
