# Generated by Django 4.1.5 on 2023-01-12 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LarParaSempre', '0007_alter_abrigo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abrigo',
            options={},
        ),
    ]
